[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "psd-recover-parameters"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "numpy>=2.0",
    "pandas",
    "scipy",
    "matplotlib",
    "pyyaml",
    "jupyter",
    "nbclient",
    "nbformat",
]

[project.optional-dependencies]
test = ["pytest"]

[tool.setuptools.packages.find]
where = ["synthetic"]
include = ["psd_synth*"]
